---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "aws-eks-asg-rolling-update-handler.name" . }}
  labels:
{{ include "aws-eks-asg-rolling-update-handler.labels" . | indent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "aws-eks-asg-rolling-update-handler.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "aws-eks-asg-rolling-update-handler.serviceAccountName" . }}
    namespace: {{ template "aws-eks-asg-rolling-update-handler.namespace" . }}