name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - run: go build -mod vendor
      - run: go test -mod vendor ./... -cover
