name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.5
      - uses: actions/checkout@v5
      - run: go build
      - run: go test ./... -cover
